##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-notification-daemon
    - autoconf-archive
    - clang
    - gcc
    - git
    - gtk3
    - libnotify
    - libwnck3
    - make
    - mate-common
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-notification-daemon
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libcanberra-gtk3-dev
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
    - libwnck-3-dev
    - libx11-dev
    - libxml2-dev
    - libxml2-utils
    - mate-common
    - quilt
    - shared-mime-info

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-notification-daemon.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - desktop-file-utils
    - file
    - git
    - libcanberra-devel
    - libnotify-devel
    - libwnck3-devel
    - libxml2-devel
    - make
    - mate-common
    - mate-desktop-devel

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libcanberra-gtk3-dev
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
    - libwnck-3-dev
    - libx11-dev
    - libxml2-dev
    - libxml2-utils
    - mate-common
    - quilt
    - shared-mime-info

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  # Install mate-common fron tarball
  - cd ${START_DIR}
  - '[ -f mate-common-1.24.1.tar.xz ] || curl -Ls -o mate-common-1.24.1.tar.xz https://github.com/mate-desktop/mate-common/releases/download/v1.24.1/mate-common-1.24.1.tar.xz'
  - tar xf mate-common-1.24.1.tar.xz
  - cd mate-common-1.24.1
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-notification-daemon-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
